const { build } = require('esbuild');
const fs = require('node:fs');
const path = require('node:path');
async function main() {
  const output = await build({ entryPoints: [path.join(__dirname, 'pdf-entry.mjs')], bundle: true, write: false, format: 'iife', platform: 'browser', target: 'es2022', minify: true, legalComments: 'inline' });
  const script = output.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
  const html = `<!doctype html><html><head><meta name="viewport" content="width=device-width"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'none'"></head><body><script>${script}</script></body></html>`;
  fs.writeFileSync(path.join(__dirname, '../src/services/pdf/runtime.generated.ts'), '// Generated by npm run generate:pdf. PDF.js is Apache-2.0 licensed.\nexport default ' + JSON.stringify(html) + ';\n');
}
main().catch(error => { console.error(error); process.exitCode = 1; });
